### ISSUE TITLE
Torrent thread 3

### ISSUE THREAD

**Issue by nick-ng** [nick-ng/PuxHelper#12]
Looks like it times out?

```
2016-02-07 13:08:26: Torrent thread broke
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/PuxHelper/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _make_request
    self, url, "Read timed out. (read timeout=%s)" % read_timeout)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='***', port=80): Read timed out. (read timeout=19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PuxHelper/PuxThreads.py", line 261, in run
    self.addShows()
  File "/home/pi/PuxHelper/PuxThreads.py", line 227, in addShows
    show.newTorrentURLs()
  File "/home/pi/PuxHelper/PuxShowf.py", line 151, in newTorrentURLs
    foundTorrents = PuxTorrents.torrentSearch(searchDict)
  File "/home/pi/PuxHelper/PuxTorrents.py", line 21, in torrentSearch
    return NoPubWebAdapters.torrentSearch(searchDict)
  File "/home/pi/PuxHelper/NoPubWebAdapters.py", line 120, in torrentSearch
    torrentList = ***Search(searchDict)
  File "/home/pi/PuxHelper/NoPubWebAdapters.py", line 25, in ***Search
    website = BFun.webRead(torrentSearchURL)
  File "/home/pi/PuxHelper/BFun.py", line 141, in webRead
    tempR = requests.get(someURL,timeout=timeout)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 422, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='***', port=80): Read timed out. (read timeout=19)
```

**Comment by nick-ng** [comment]
Seems to be solved by #13
